# Generated by Django 2.2 on 2019-05-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('surname', models.CharField(db_index=True, max_length=150)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('patronymic', models.CharField(db_index=True, max_length=150)),
                ('passport', models.CharField(db_index=True, max_length=50)),
                ('address', models.CharField(db_index=True, max_length=150)),
                ('city', models.CharField(db_index=True, max_length=150)),
                ('telephone', models.CharField(db_index=True, max_length=20)),
                ('birthday', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
