# Generated by Django 2.2 on 2019-05-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('transport', models.CharField(db_index=True, max_length=150)),
                ('house_night', models.CharField(db_index=True, max_length=150)),
                ('type_food', models.CharField(db_index=True, max_length=150)),
                ('price_per_day', models.CharField(db_index=True, max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='tours',
            field=models.ManyToManyField(blank=True, related_name='customers', to='main.Tour'),
        ),
    ]
