# Generated by Django 2.2 on 2019-05-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190504_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('address', models.CharField(db_index=True, max_length=150)),
                ('city', models.CharField(db_index=True, max_length=150)),
                ('telephone', models.CharField(db_index=True, max_length=20)),
                ('description', models.CharField(db_index=True, max_length=150)),
                ('rooms', models.IntegerField(db_index=True)),
                ('swimming_pool', models.BooleanField(db_index=True)),
                ('medical_services', models.BooleanField(db_index=True)),
                ('spa', models.BooleanField(db_index=True)),
                ('level', models.IntegerField(db_index=True)),
                ('distance', models.IntegerField(db_index=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['surname']},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
