# Generated by Django 2.2 on 2019-05-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190507_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('arrival_date', models.DateTimeField()),
                ('departure_date', models.DateTimeField()),
                ('childrens', models.BooleanField(db_index=True)),
                ('medical_insurance', models.BooleanField(db_index=True)),
                ('people', models.IntegerField(db_index=True)),
                ('price', models.IntegerField(db_index=True)),
                ('customers', models.ManyToManyField(blank=True, related_name='vouchers', to='main.Customer')),
                ('pensions', models.ManyToManyField(blank=True, related_name='vouchers', to='main.Pension')),
                ('tours', models.ManyToManyField(blank=True, related_name='vouchers', to='main.Tour')),
            ],
            options={
                'ordering': ['arrival_date'],
            },
        ),
    ]
