# Generated by Django 2.2 on 2019-05-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_housing'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='housings',
            field=models.ManyToManyField(blank=True, related_name='vouchers', to='main.Housing'),
        ),
    ]
